/**
 * @file HTTP Status codes and messages
 */

const HTTP_STATUS = {
  // Success
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,

  // Client errors
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,

  // Server errors
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  SERVICE_UNAVAILABLE: 503,
};

const ERROR_CODES = {
  // Auth errors
  INVALID_TOKEN: "INVALID_TOKEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  NO_TOKEN_PROVIDED: "NO_TOKEN_PROVIDED",
  UNAUTHORIZED_ROLE: "UNAUTHORIZED_ROLE",

  // User errors
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  INVALID_EMAIL: "INVALID_EMAIL",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  ACCOUNT_INACTIVE: "ACCOUNT_INACTIVE",

  // Validation errors
  VALIDATION_ERROR: "VALIDATION_ERROR",
  MISSING_REQUIRED_FIELD: "MISSING_REQUIRED_FIELD",
  INVALID_INPUT: "INVALID_INPUT",

  // Resource errors
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  OPERATION_NOT_ALLOWED: "OPERATION_NOT_ALLOWED",
  CONFLICT_ERROR: "CONFLICT_ERROR",

  // Server errors
  DATABASE_ERROR: "DATABASE_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  FILE_UPLOAD_ERROR: "FILE_UPLOAD_ERROR",
};

module.exports = {
  HTTP_STATUS,
  ERROR_CODES,
};
