/**
 * @file Central export for all constants
 */

const {
  USER_ROLES,
  USER_STATUS,
  EVENT_REPORT_STATUS,
  FILE_REVIEW_STATUS,
  RESPONSIBILITY_STATUS,
  PLACEMENT_STATUS,
  EVENT_TYPES,
  PAGINATION,
} = require("./enums");
const { HTTP_STATUS, ERROR_CODES } = require("./http-status");

module.exports = {
  // Enums
  USER_ROLES,
  USER_STATUS,
  EVENT_REPORT_STATUS,
  FILE_REVIEW_STATUS,
  RESPONSIBILITY_STATUS,
  PLACEMENT_STATUS,
  EVENT_TYPES,
  PAGINATION,
  // HTTP
  HTTP_STATUS,
  ERROR_CODES,
};
